receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:
  prometheus:
    endpoint: "0.0.0.0:8889"
  prometheusremotewrite:
    endpoint: "victoriametrics:8428"

processors:
  batch:

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus, logging, prometheusremotewrite]
      processors: [batch]